jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."

  SecurityRealm:
    local:
      allowsSignup: false
      users:
        - id: "chocolateen"
          name: "Hugo"
          password: ${USER_CHOCOLATEEN_PASSWORD}
        - id: "vaugie_g"
          name: "Garance"
          password: ${USER_VAUGIE_G_PASSWORD}
        - id: "i_dont_know"
          name: "Jeremy"
          password: ${USER_I_DONT_KNOW_PASSWORD}
        - id: "nasso"
          name: "Nassim"
          password: ${USER_NASSO_PASSWORD}
          
  AuthorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions: ["Overall/Administer"]
          - name: "ape"
            description: "Pedagogical team member"
            permissions: ["Job/Build", "Job/Workspace", "Job/View"]
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permissions: ["Job/Build", "Job/Workspace", "Job/Configure", "Job/Create", "Job/Delete", "Job/Cancel", "Job/View"]
          - name: "assist"
            description: "Assistant"
            permissions: ["Job/View", "Job/Workspace"]

jobs:
  - file: "/var/jenkins_home/job_dsl.groovy"
